"""Render converted targets as a single CMakeLists.txt."""

import os

HEADER = """\
# Generated by builder from the Android.bp files of the fetched AOSP sources
# (os={os}, arch={arch}). Do not edit: change the overlay .bp files instead.
cmake_minimum_required(VERSION 3.27)
project(android_sdk_custom C CXX ASM)

set(AOSP "${{CMAKE_CURRENT_LIST_DIR}}/aosp")   # AOSP-layout symlink farm
set(GEN "${{CMAKE_CURRENT_LIST_DIR}}/gen")     # codegen outputs
set(SDK "{sdk}")                               # this repo (overlay files)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${{CMAKE_BINARY_DIR}}/bin")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${{CMAKE_BINARY_DIR}}/lib")
"""


def q(s):
    """Quote one CMake argument."""
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    # keep our own ${VAR} references live; escape any other $
    out, i = [], 0
    while i < len(s):
        if s.startswith("${", i) and s.find("}", i) > 0:
            j = s.find("}", i)
            name = s[i + 2:j]
            if name.replace("_", "").isalnum() and name.isupper():
                out.append(s[i:j + 1])
                i = j + 1
                continue
        out.append("\\$" if s[i] == "$" and not s.startswith("$<", i) else s[i])
        i += 1
    s = "".join(out).replace(";", "\\;")
    return '"%s"' % s


def gx(s):
    """Escape a flag for use inside a $<cond:...> generator expression."""
    return s.replace("$", "$<1:$>").replace(">", "$<ANGLE-R>").replace(",", "$<COMMA>") \
        .replace(";", "$<SEMICOLON>")


def lang_flags(lang, flags):
    if not flags:
        return None
    return '"$<$<COMPILE_LANGUAGE:%s>:%s>"' % (
        lang, ";".join(gx(f).replace("\\", "\\\\").replace('"', '\\"') for f in flags))


class Emitter:
    def __init__(self, conv, tools, sdk_root, global_includes, needs, globals_=None):
        self.conv, self.tools, self.sdk = conv, tools, sdk_root
        self.global_includes = global_includes
        self.needs = needs
        self.globals = globals_ or {}
        self.lines = []

    def w(self, line=""):
        self.lines.append(line)

    def block(self, head, items, indent="    "):
        items = [i for i in items if i]
        if not items:
            return
        self.w(head)
        for i in items:
            self.w(indent + i)
        self.w(")")

    def render(self):
        c = self.conv
        self.w(HEADER.format(os=c.os.name, arch=c.arch, sdk=self.sdk.replace("\\", "/")))
        if "protoc" in self.needs:
            self.w('if(NOT PROTOC)\n    message(FATAL_ERROR "pass -DPROTOC=<host protoc> (see scripts/build.sh)")\nendif()')
        if "bison" in self.needs:
            self.w("find_program(BISON bison REQUIRED)")
        if "flex" in self.needs:
            self.w("find_program(FLEX flex REQUIRED)")
        if self.global_includes:
            self.block("include_directories(SYSTEM", [q(i) for i in self.global_includes])
        g = self.globals
        self.block("add_compile_options(", [
            lang_flags("C,CXX", g.get("cflags", [])),
            lang_flags("C", g.get("conlyflags", [])),
            lang_flags("CXX", g.get("cppflags", [])),
            lang_flags("ASM", g.get("asflags", [])),
        ])
        self.block("add_link_options(", [q(f) for f in g.get("ldflags", [])])
        self.w()
        for t in sorted(c.order, key=lambda t: t.name):
            if t.kind == "filegroup":
                continue
            self.w("# %s (%s) %s" % (t.soong_name, t.module.type, self._where(t.module)))
            getattr(self, "_" + t.kind)(t)
            self.w()
        # `ninja sdk_tools` builds just the tools (plain `ninja` builds the same)
        self.w("add_custom_target(sdk_tools)")
        self.block("add_dependencies(sdk_tools", list(self.tools))
        return "\n".join(self.lines) + "\n"

    def _where(self, m):
        if m.overlay:
            return "overlay " + os.path.basename(m.path)
        return (m.aosp_dir or ".") + "/" + os.path.basename(m.path)

    # -- target kinds

    def _gen(self, t):
        for g in t.gens:
            self._custom_command(g)
        self.w("add_library(%s INTERFACE)" % t.name)
        self.block("target_sources(%s INTERFACE" % t.name, [q(s) for s in t.interface_sources])
        self.block("target_include_directories(%s INTERFACE" % t.name,
                   [q(i) for i in t.export_includes])

    def _custom_command(self, g):
        if isinstance(g.script, list):
            cmd = " ".join(q(a) for a in g.script)
        else:
            cmd = "bash " + q(g.script)
        dirs = sorted({o.rsplit("/", 1)[0] for o in g.outputs})
        self.w("add_custom_command(")
        self.w("    OUTPUT " + " ".join(q(o) for o in g.outputs))
        self.w("    COMMAND ${CMAKE_COMMAND} -E make_directory " + " ".join(q(d) for d in dirs))
        self.w("    COMMAND " + cmd)
        if g.depends:
            self.w("    DEPENDS " + " ".join(q(d) for d in g.depends))
        self.w('    WORKING_DIRECTORY "${AOSP}"')
        self.w("    COMMENT %s" % q(g.comment))
        self.w("    VERBATIM)")

    def _prebuilt(self, t):
        self.w("add_library(%s STATIC IMPORTED GLOBAL)" % t.name)
        self.w("set_target_properties(%s PROPERTIES IMPORTED_LOCATION %s)" % (t.name, q(t.prebuilt)))
        self.block("target_include_directories(%s INTERFACE" % t.name, [q(i) for i in t.export_includes])
        self._links(t, "INTERFACE", "INTERFACE")
        self.block("target_link_libraries(%s INTERFACE" % t.name, [q(l) for l in t.ldlibs])

    def _headers(self, t):
        self.w("add_library(%s INTERFACE)" % t.name)
        self.block("target_include_directories(%s INTERFACE" % t.name, [q(i) for i in t.export_includes])
        self.block("target_include_directories(%s SYSTEM INTERFACE" % t.name,
                   [q(i) for i in t.export_system_includes])
        self._links(t, "INTERFACE", "INTERFACE")

    def _static(self, t):
        srcs = t.srcs
        compiled = [s for s in srcs if os.path.splitext(s)[1] in (".c", ".cc", ".cpp", ".cxx", ".c++", ".S", ".s")]
        if not compiled and not t.objs:
            # Nothing to archive: an aggregation of whole_static_libs or a
            # header-only static lib. Model it as an interface.
            for g in t.gens:
                self._custom_command(g)
            self.w("add_library(%s INTERFACE)" % t.name)
            self.block("target_sources(%s INTERFACE" % t.name, [q(s) for s in srcs])
            self.block("target_include_directories(%s INTERFACE" % t.name,
                       [q(i) for i in t.export_includes])
            self._links(t, "INTERFACE", "INTERFACE")
            self.block("target_link_libraries(%s INTERFACE" % t.name, [q(l) for l in t.ldlibs])
            return
        self._compiled(t, "add_library(%s STATIC" % t.name)
        self.block("target_link_libraries(%s INTERFACE" % t.name, [q(l) for l in t.ldlibs])

    def _object(self, t):
        self._compiled(t, "add_library(%s OBJECT" % t.name)

    def _binary(self, t):
        self._compiled(t, "add_executable(%s" % t.name)
        if t.output_name and t.output_name != t.name:
            self.w("set_target_properties(%s PROPERTIES OUTPUT_NAME %s)" % (t.name, q(t.output_name)))
        # A library whole-linked somewhere below this binary is usually also
        # a plain dependency of another library, and CMake refuses one link
        # item with two features. Soong lets whole-archive win; so does this.
        whole = self._whole_below(t)
        if whole:
            self.w("set_property(TARGET %s PROPERTY LINK_LIBRARY_OVERRIDE %s)"
                   % (t.name, q(",".join(["WHOLE_ARCHIVE"] + whole))))
        ldlibs = list(dict.fromkeys(t.ldlibs + self.globals.get("ldlibs", [])))
        self.block("target_link_libraries(%s PRIVATE" % t.name, [q(l) for l in ldlibs])
        self.block("target_link_options(%s PRIVATE" % t.name, [q(f) for f in t.ldflags])

    def _compiled(self, t, head):
        for g in t.gens:
            self._custom_command(g)
        self.block(head, [q(s) for s in t.srcs])
        # a library sees its own exported dirs first (library.go compilerFlags)
        pub = "PRIVATE" if t.kind == "binary" else "PUBLIC"
        self.block("target_include_directories(%s %s" % (t.name, pub), [q(i) for i in t.export_includes])
        self.block("target_include_directories(%s SYSTEM %s" % (t.name, pub),
                   [q(i) for i in t.export_system_includes])
        self.block("target_include_directories(%s PRIVATE" % t.name, [q(i) for i in t.includes])
        self.block("target_compile_options(%s PRIVATE" % t.name, [
            lang_flags("C,CXX", t.cflags),
            lang_flags("C", ["-std=" + t.c_std] + t.conlyflags),
            lang_flags("CXX", ["-std=" + t.cpp_std] + t.cppflags),
            lang_flags("ASM", ["-D__ASSEMBLY__"] + t.asflags),
        ])
        for o in t.objs:
            self.w("target_link_libraries(%s PRIVATE %s)" % (t.name, o.name))
        self._links(t, "PUBLIC" if t.kind != "binary" else "PRIVATE", "PRIVATE")

    @staticmethod
    def _whole_below(t):
        """Libraries linked WHOLE_ARCHIVE anywhere in t's link graph.

        Every non-header link reaches the final link line (a static
        library's private deps too, as $<LINK_ONLY:>), so walk them all.
        """
        whole, seen, stack = [], {id(t)}, [t]
        while stack:
            x = stack.pop()
            deps = [(d, mode) for d, _, mode in x.link] + [(o, "link") for o in x.objs]
            for d, mode in deps:
                if d is x or d.kind == "filegroup":
                    continue
                if mode == "headers" and d.kind in ("static", "object", "binary"):
                    continue  # $<COMPILE_ONLY:>, see _links()
                if mode == "whole" and d.kind in ("static", "prebuilt") and d.name not in whole:
                    whole.append(d.name)
                if id(d) not in seen:
                    seen.add(id(d))
                    stack.append(d)
        return sorted(whole)

    def _links(self, t, pub_kw, priv_kw):
        pub, priv = [], []
        for d, public, mode in t.link:
            if d is t or d.kind == "filegroup":
                continue
            if mode == "headers" and d.kind in ("static", "object", "binary"):
                item = "$<COMPILE_ONLY:%s>" % d.name
            elif mode == "whole" and d.kind in ("static", "prebuilt"):
                item = "$<LINK_LIBRARY:WHOLE_ARCHIVE,%s>" % d.name
            else:
                item = d.name
            (pub if public else priv).append(item)
        dedup = lambda l: list(dict.fromkeys(l))
        self.block("target_link_libraries(%s %s" % (t.name, pub_kw), [q(x) if "$<" in x else x for x in dedup(pub)])
        self.block("target_link_libraries(%s %s" % (t.name, priv_kw), [q(x) if "$<" in x else x for x in dedup(priv)])
