name: Make SDK (Linux)
run-name: Make SDK ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Platform Tools Version"
        required: true
        default: "36.0.2"
      tag:
        description: "Android Source Tag"
        required: true
        default: "android-16.0.0_r4"

permissions:
  contents: write
  packages: read

jobs:
  make:
    uses: ./.github/workflows/make-sdk.yml
    secrets: inherit
    with:
      platform: linux
      version: ${{ inputs.version }}
      tag: ${{ inputs.tag }}
      # powerpc64le-linux-gnu, x86_64-linux-gnux32,
      # mips-linux-gnueabi, mips-linux-gnueabihf, mips-linux-musleabi,
      # mips-linux-musleabihf, mips64-linux-gnuabin32, mips64-linux-gnuabi64,
      # mips64-linux-muslabin32, mips64-linux-muslabi64,
      # mips64el-linux-gnuabin32, mips64el-linux-gnuabi64,
      # mips64el-linux-muslabin32, mips64el-linux-muslabi64,
      # mipsel-linux-gnueabi, mipsel-linux-gnueabihf,
      # mipsel-linux-musleabi, mipsel-linux-musleabihf,
      # thumb-linux-musleabi, thumb-linux-musleabihf,
      # thumbeb-linux-musleabi, thumbeb-linux-musleabihf
      targets: >-
        ["hexagon-linux-musl"]
