name: Make SDK (macOS)
run-name: Make SDK ${{ inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "AOSP source tag (android-* or platform-tools-*)"
        required: true
        default: "android-17.0.0_r1"

permissions:
  contents: write
  packages: read

jobs:
  make:
    uses: ./.github/workflows/make-sdk.yml
    secrets: inherit
    with:
      platform: macos
      tag: ${{ inputs.tag }}
      targets: >-
        ["x86_64-apple-darwin", "x86_64h-apple-darwin",
         "arm64-apple-darwin", "arm64e-apple-darwin"]
